# Generated by Django 5.2.6 on 2025-09-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id_ong', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ong', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('case_id', models.CharField()),
                ('ong_originante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app.ong')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('disponible_para_ayudar', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='app.proyecto')),
            ],
        ),
    ]
