# Generated by Django 5.2.6 on 2025-10-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_id',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
