# Generated by Django 5.2.6 on 2025-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='cloud_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cloud_id',
        ),
        migrations.AddField(
            model_name='etapa',
            name='cant_aporte_actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
