# Generated by Django 5.2.6 on 2025-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_etapa_cloud_id_remove_project_cloud_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ejecucion', 'En ejecucion'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
    ]
