# Generated by Django 5.2.7 on 2025-11-17 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_observation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ongs_colaboradoras',
            field=models.ManyToManyField(blank=True, help_text='ONGs que han colaborado/aportado en este proyecto', related_name='proyectos_colaborados', to=settings.AUTH_USER_MODEL),
        ),
    ]
