# Generated by Django 5.2.6 on 2025-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_ong_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='case_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cubierto', 'Cubierto'), ('En ejecucion', 'En ejecucion'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
    ]
