# Generated by Django 5.2.6 on 2025-11-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projectplanning', '0005_alter_project_id_back_ong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromiso',
            old_name='etapa_cloud',
            new_name='id_etapa',
        ),
        migrations.RenameField(
            model_name='etapa',
            old_name='proyecto_cloud',
            new_name='proyecto',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='es_total',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='id_etapa_back',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='id_back_etapa',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='id_proyecto_back',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_back_proyecto',
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='id_ong_coolaboradora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_back_ong',
            field=models.IntegerField(),
        ),
    ]
